menu:
  title: "{section} Settings"
  button:
    next:
      type: ARROW
      name: "Next page"
      lore:
        - "Click me!"
    back:
      type: ARROW
      name: "Previous page"
      lore:
        - "Click me!"
    done:
      type: BARRIER
      name: "Done"
      lore:
        - "Goes back to last menu,"
        - "or closes the current menu."