menu:
  title: "Manage Enchants for {name}"
  button:
    upgrade:
      name: "+{levels} Enchant Levels"
      lore:
        - "Upgrade Enchant {name}"
        - "&cNet Cost: &f${netCost}"
        - "&cNew Chance: &f{newChance}%"
        - "&cNew Level &f{newLevel}&c/&f{maxLevel}"
        - "&cMax Chance: &f{maxChance}%"
        - "&cMax Cost: &f${maxCost}"
        - "&cLevel: &f{currentLevel}&c/&f{maxLevel}"
        - "&cCurrent Chance: &f{currentChance}%"
        - "&cCurrent Cost: &f${currentCost}"
        - "click to purchase"